#
CONFIG_ESB=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=252

# CONFIG_UART_ASYNC_API=y
# CONFIG_UART_WIDE_DATA=y
CONFIG_GPIO=y
CONFIG_MAIN_STACK_SIZE=8096

CONFIG_STDOUT_CONSOLE=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="LFPRecordingSample"
CONFIG_USB_DEVICE_PID=0x0001
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n

# about 5s in 6.1ms one package
CONFIG_USB_CDC_ACM_RINGBUF_SIZE=30000 
CONFIG_USB_CDC_ACM=y
CONFIG_SOC_SERIES_NRF52X=y

# 注意： 在dongle 中 log 会占用uart的通道, 同时需要配置好uart 所使用的config
# CONFIG_LOG=y
# CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
# CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y
CONFIG_LOG_BACKEND_UART=y # nrf-dongle: y
