# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\bcila\Desktop\XHZ\PYQT_BLE2\BLE_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1579, 906)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dataFrame = QtWidgets.QFrame(self.centralwidget)
        self.dataFrame.setGeometry(QtCore.QRect(560, 10, 1001, 831))
        self.dataFrame.setStyleSheet("QFrame {border-width:2px;border-style:solid;border-color:rgb(208,208,208);background:#F0F0F0}\n"
"QLabel {border-width:0px}")
        self.dataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataFrame.setObjectName("dataFrame")
        self.layoutWidget = QtWidgets.QWidget(self.dataFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 981, 811))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.DataGraph_3 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_3.setObjectName("DataGraph_3")
        self.gridLayout_2.addWidget(self.DataGraph_3, 1, 0, 1, 1)
        self.DataGraph_2 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_2.setObjectName("DataGraph_2")
        self.gridLayout_2.addWidget(self.DataGraph_2, 0, 1, 1, 1)
        self.DataGraph_7 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_7.setObjectName("DataGraph_7")
        self.gridLayout_2.addWidget(self.DataGraph_7, 3, 0, 1, 1)
        self.DataGraph_4 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_4.setObjectName("DataGraph_4")
        self.gridLayout_2.addWidget(self.DataGraph_4, 1, 1, 1, 1)
        self.DataGraph_5 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_5.setObjectName("DataGraph_5")
        self.gridLayout_2.addWidget(self.DataGraph_5, 2, 0, 1, 1)
        self.DataGraph_6 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_6.setObjectName("DataGraph_6")
        self.gridLayout_2.addWidget(self.DataGraph_6, 2, 1, 1, 1)
        self.DataGraph_8 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_8.setObjectName("DataGraph_8")
        self.gridLayout_2.addWidget(self.DataGraph_8, 3, 1, 1, 1)
        self.DataGraph_1 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_1.setObjectName("DataGraph_1")
        self.gridLayout_2.addWidget(self.DataGraph_1, 0, 0, 1, 1)
        self.DataGraph_10 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_10.setObjectName("DataGraph_10")
        self.gridLayout_2.addWidget(self.DataGraph_10, 4, 1, 1, 1)
        self.DataGraph_11 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_11.setObjectName("DataGraph_11")
        self.gridLayout_2.addWidget(self.DataGraph_11, 5, 0, 1, 1)
        self.DataGraph_12 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_12.setObjectName("DataGraph_12")
        self.gridLayout_2.addWidget(self.DataGraph_12, 5, 1, 1, 1)
        self.DataGraph_13 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_13.setObjectName("DataGraph_13")
        self.gridLayout_2.addWidget(self.DataGraph_13, 6, 0, 1, 1)
        self.DataGraph_14 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_14.setObjectName("DataGraph_14")
        self.gridLayout_2.addWidget(self.DataGraph_14, 6, 1, 1, 1)
        self.DataGraph_9 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_9.setObjectName("DataGraph_9")
        self.gridLayout_2.addWidget(self.DataGraph_9, 4, 0, 1, 1)
        self.DataGraph_16 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_16.setObjectName("DataGraph_16")
        self.gridLayout_2.addWidget(self.DataGraph_16, 7, 1, 1, 1)
        self.DataGraph_15 = GraphicsLayoutWidget(self.layoutWidget)
        self.DataGraph_15.setObjectName("DataGraph_15")
        self.gridLayout_2.addWidget(self.DataGraph_15, 7, 0, 1, 1)
        self.BLEFrame = QtWidgets.QFrame(self.centralwidget)
        self.BLEFrame.setGeometry(QtCore.QRect(10, 10, 541, 561))
        self.BLEFrame.setStyleSheet("QFrame {border-width:2px;border-style:solid;border-color:rgb(208,208,208);background:#F0F0F0}\n"
"QLabel {border-width:0px}\n"
"QTextEdit {background:#FFFFFF}")
        self.BLEFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BLEFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BLEFrame.setObjectName("BLEFrame")
        self.layoutWidget1 = QtWidgets.QWidget(self.BLEFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 521, 531))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Scan_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.Scan_Btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Scan_Btn.setFont(font)
        self.Scan_Btn.setObjectName("Scan_Btn")
        self.horizontalLayout.addWidget(self.Scan_Btn)
        self.Connect_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.Connect_Btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Connect_Btn.setFont(font)
        self.Connect_Btn.setObjectName("Connect_Btn")
        self.horizontalLayout.addWidget(self.Connect_Btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Scan_CB = QtWidgets.QComboBox(self.layoutWidget1)
        self.Scan_CB.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Scan_CB.setFont(font)
        self.Scan_CB.setObjectName("Scan_CB")
        self.horizontalLayout_9.addWidget(self.Scan_CB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.Server_CB = QtWidgets.QComboBox(self.layoutWidget1)
        self.Server_CB.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Server_CB.setFont(font)
        self.Server_CB.setObjectName("Server_CB")
        self.horizontalLayout_5.addWidget(self.Server_CB)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.Character_CB = QtWidgets.QComboBox(self.layoutWidget1)
        self.Character_CB.setMinimumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Character_CB.setFont(font)
        self.Character_CB.setObjectName("Character_CB")
        self.horizontalLayout_6.addWidget(self.Character_CB)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.DataSend_Line = QtWidgets.QLineEdit(self.layoutWidget1)
        self.DataSend_Line.setMinimumSize(QtCore.QSize(50, 70))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.DataSend_Line.setFont(font)
        self.DataSend_Line.setObjectName("DataSend_Line")
        self.horizontalLayout_2.addWidget(self.DataSend_Line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Hex_Cb = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Hex_Cb.setFont(font)
        self.Hex_Cb.setObjectName("Hex_Cb")
        self.verticalLayout.addWidget(self.Hex_Cb)
        self.DataSend_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.DataSend_Btn.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.DataSend_Btn.setFont(font)
        self.DataSend_Btn.setObjectName("DataSend_Btn")
        self.verticalLayout.addWidget(self.DataSend_Btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.DataRead_Text = QtWidgets.QTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.DataRead_Text.setFont(font)
        self.DataRead_Text.setObjectName("DataRead_Text")
        self.gridLayout.addWidget(self.DataRead_Text, 2, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.DataRead_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.DataRead_Btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.DataRead_Btn.setFont(font)
        self.DataRead_Btn.setObjectName("DataRead_Btn")
        self.horizontalLayout_3.addWidget(self.DataRead_Btn)
        self.DataReadCont_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.DataReadCont_Btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.DataReadCont_Btn.setFont(font)
        self.DataReadCont_Btn.setObjectName("DataReadCont_Btn")
        self.horizontalLayout_3.addWidget(self.DataReadCont_Btn)
        self.DataNotify_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.DataNotify_Btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.DataNotify_Btn.setFont(font)
        self.DataNotify_Btn.setObjectName("DataNotify_Btn")
        self.horizontalLayout_3.addWidget(self.DataNotify_Btn)
        self.ClearData_Btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.ClearData_Btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.ClearData_Btn.setFont(font)
        self.ClearData_Btn.setObjectName("ClearData_Btn")
        self.horizontalLayout_3.addWidget(self.ClearData_Btn)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_2.setStretch(5, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.BLEState_Label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.BLEState_Label.setFont(font)
        self.BLEState_Label.setObjectName("BLEState_Label")
        self.verticalLayout_3.addWidget(self.BLEState_Label)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 580, 541, 261))
        self.frame.setStyleSheet("QFrame {border-width:2px;border-style:solid;border-color:rgb(208,208,208);background:#F0F0F0}\n"
"QLabel {border-width:0px}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 190, 521, 52))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.Channel_CB = QtWidgets.QComboBox(self.layoutWidget2)
        self.Channel_CB.setMinimumSize(QtCore.QSize(250, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Channel_CB.setFont(font)
        self.Channel_CB.setObjectName("Channel_CB")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.Channel_CB.addItem("")
        self.horizontalLayout_8.addWidget(self.Channel_CB)
        self.DataCheck_Btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.DataCheck_Btn.setMinimumSize(QtCore.QSize(0, 45))
        self.DataCheck_Btn.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.DataCheck_Btn.setFont(font)
        self.DataCheck_Btn.setObjectName("DataCheck_Btn")
        self.horizontalLayout_8.addWidget(self.DataCheck_Btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 211, 128))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.DataRecStop_Btn = QtWidgets.QPushButton(self.widget)
        self.DataRecStop_Btn.setMinimumSize(QtCore.QSize(0, 50))
        self.DataRecStop_Btn.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.DataRecStop_Btn.setFont(font)
        self.DataRecStop_Btn.setObjectName("DataRecStop_Btn")
        self.horizontalLayout_10.addWidget(self.DataRecStop_Btn)
        self.ClearPG_Btn = QtWidgets.QPushButton(self.widget)
        self.ClearPG_Btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.ClearPG_Btn.setFont(font)
        self.ClearPG_Btn.setObjectName("ClearPG_Btn")
        self.horizontalLayout_10.addWidget(self.ClearPG_Btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.SampleRate_LE = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.SampleRate_LE.setFont(font)
        self.SampleRate_LE.setObjectName("SampleRate_LE")
        self.horizontalLayout_11.addWidget(self.SampleRate_LE)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.SignalLen_LE = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.SignalLen_LE.setFont(font)
        self.SignalLen_LE.setObjectName("SignalLen_LE")
        self.horizontalLayout_12.addWidget(self.SignalLen_LE)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1579, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Scan_Btn.setText(_translate("MainWindow", "搜索"))
        self.Connect_Btn.setText(_translate("MainWindow", "连接"))
        self.label_3.setText(_translate("MainWindow", "服务"))
        self.label_4.setText(_translate("MainWindow", "特征"))
        self.label_5.setText(_translate("MainWindow", "数据发送："))
        self.Hex_Cb.setText(_translate("MainWindow", "十六进制"))
        self.DataSend_Btn.setText(_translate("MainWindow", "发送"))
        self.label_2.setText(_translate("MainWindow", "读取数据："))
        self.DataRead_Btn.setText(_translate("MainWindow", "读取"))
        self.DataReadCont_Btn.setText(_translate("MainWindow", "连续读取"))
        self.DataNotify_Btn.setText(_translate("MainWindow", "订阅"))
        self.ClearData_Btn.setText(_translate("MainWindow", "清除数据"))
        self.BLEState_Label.setText(_translate("MainWindow", "状态："))
        self.label_6.setText(_translate("MainWindow", "选择通道："))
        self.Channel_CB.setItemText(0, _translate("MainWindow", "None channel"))
        self.Channel_CB.setItemText(1, _translate("MainWindow", "channel1"))
        self.Channel_CB.setItemText(2, _translate("MainWindow", "channel2"))
        self.Channel_CB.setItemText(3, _translate("MainWindow", "channel3"))
        self.Channel_CB.setItemText(4, _translate("MainWindow", "channel4"))
        self.Channel_CB.setItemText(5, _translate("MainWindow", "channel5"))
        self.Channel_CB.setItemText(6, _translate("MainWindow", "channel6"))
        self.Channel_CB.setItemText(7, _translate("MainWindow", "channel7"))
        self.Channel_CB.setItemText(8, _translate("MainWindow", "channel8"))
        self.Channel_CB.setItemText(9, _translate("MainWindow", "channel9"))
        self.Channel_CB.setItemText(10, _translate("MainWindow", "channel10"))
        self.Channel_CB.setItemText(11, _translate("MainWindow", "channel11"))
        self.Channel_CB.setItemText(12, _translate("MainWindow", "channel12"))
        self.Channel_CB.setItemText(13, _translate("MainWindow", "channel13"))
        self.Channel_CB.setItemText(14, _translate("MainWindow", "channel14"))
        self.Channel_CB.setItemText(15, _translate("MainWindow", "channel15"))
        self.Channel_CB.setItemText(16, _translate("MainWindow", "channel16"))
        self.DataCheck_Btn.setText(_translate("MainWindow", "查看"))
        self.DataRecStop_Btn.setText(_translate("MainWindow", "开始接收"))
        self.ClearPG_Btn.setText(_translate("MainWindow", "清除画面"))
        self.label.setText(_translate("MainWindow", "信号采样率："))
        self.label_7.setText(_translate("MainWindow", "信号窗长度："))

from pyqtgraph import GraphicsLayoutWidget
