# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\博士资料\主要工作\植入式大鼠机器人\软件设计\PyQt\Channel_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets 
from PyQt6.QtWidgets import (QApplication, QComboBox, QFrame, QHBoxLayout,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QTextBrowser,
    QVBoxLayout, QWidget ,QMessageBox)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.rect = QApplication.instance().screens()[0].size()

        self.height = int(self.rect.height()*0.9 )
        self.width = int(self.rect.width()*0.55 )
        Form.resize(self.width,self.height)


        self.dataFrame = QtWidgets.QFrame(Form)
        self.dataFrame.setGeometry(QtCore.QRect(10, 10,  self.width * 0.95 ,self.height *0.5))
        self.dataFrame.setStyleSheet("QFrame {border-width:2px;border-style:solid;border-color:rgb(208,208,208);background:#F0F0F0}\n"
"QLabel {border-width:0px}")
        self.dataFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dataFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dataFrame.setObjectName("dataFrame")

        self.dataFrame1 = QtWidgets.QFrame(Form)
        self.dataFrame1.setGeometry(QtCore.QRect(10, self.width *0.48, self.width * 0.95 ,self.height *0.45))
        self.dataFrame1.setStyleSheet("QFrame {border-width:2px;border-style:solid;border-color:rgb(208,208,208);background:#F0F0F0}\n"
            "QLabel {border-width:0px}")
        self.dataFrame1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dataFrame1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dataFrame1.setObjectName("dataFrame1")

        

        self.DataGraph_2 = GraphicsLayoutWidget(self.dataFrame1)
        self.DataGraph_2.setGeometry(QtCore.QRect(10, 60, self.width * 0.90, self.height *0.4)) # 注意 这个坐标是在dataframe 内的相对坐标
        self.DataGraph_2.setObjectName("raster data")

        self.DataGraph_1 = GraphicsLayoutWidget(self.dataFrame)
        self.DataGraph_1.setGeometry(QtCore.QRect(10, 70, self.width * 0.90, self.height *0.4))
        self.DataGraph_1.setObjectName("raw data")

        self.Channel_Label = QtWidgets.QLabel(self.dataFrame)
        self.Channel_Label.setGeometry(QtCore.QRect(10, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Channel_Label.setFont(font)
        self.Channel_Label.setObjectName("Channel_Label")

        self.Channel_Label2 = QtWidgets.QLabel(self.dataFrame1)
        self.Channel_Label2.setGeometry(QtCore.QRect(10, 10, 111, 41))
        font1 = QtGui.QFont()
        font1.setFamily("微软雅黑")
        font1.setPointSize(12)
        self.Channel_Label2.setFont(font)
        self.Channel_Label2.setObjectName("Spike data")

        self.SetTimeFreq_Btn = QtWidgets.QPushButton(self.dataFrame)
        self.SetTimeFreq_Btn.setGeometry(QtCore.QRect(10, self.height *0.4 + 70, 121, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.SetTimeFreq_Btn.setFont(font)
        self.SetTimeFreq_Btn.setObjectName("SetTimeFreq_Btn")
        self.SetFilter_Btn = QtWidgets.QPushButton(self.dataFrame)
        self.SetFilter_Btn.setGeometry(QtCore.QRect(140, self.height *0.4 + 70, 121, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.SetFilter_Btn.setFont(font)
        self.SetFilter_Btn.setObjectName("SetFilter_Btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Channel_Label.setText(_translate("Form", "通道："))
        self.Channel_Label2.setText(_translate("Form", "Spike:"))
        self.SetTimeFreq_Btn.setText(_translate("Form", "转换频域"))
        self.SetFilter_Btn.setText(_translate("Form", "设置滤波器"))
from pyqtgraph import GraphicsLayoutWidget
