
# CONFIG_MAIN_STACK_SIZE=1024 # stack size variable
# CONFIG_HEAP_MEM_POOL_SIZE=4096 # heap size: malloc() 

# nrfx marco
CONFIG_NRFX_SPIM1=y  # for lsm
CONFIG_NRFX_SPIM2=y # for lsm and rhd init
CONFIG_NRFX_SPIM3=y

# for debugging
CONFIG_LOG=y

# for embedding boards
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y # enable p0.00 ;p0.01 as GPIO
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=n   # 新增
CONFIG_SOC_ENABLE_LFXO=n

CONFIG_SOC_SERIES_NRF52X=y

# Enable RTT
CONFIG_USE_SEGGER_RTT=y

# enable GPIO
CONFIG_GPIO=y

# enable uart driver
CONFIG_SERIAL=y

# enable console
# CONFIG_CONSOLE=y
# CONFIG_UART_CONSOLE=y

# other
CONFIG_GPIO_NRFX=y
CONFIG_NRFX_PPI=y
CONFIG_NRFX_GPIOTE0=y
CONFIG_NRFX_TIMER1=y # for spi sampling
CONFIG_NRFX_TIMER2=y # for esb
CONFIG_NRFX_TIMER3=y # for spi reset

# CONFIG_UART_NRFX=y
# CONFIG_UART_ASYNC_API=y
# CONFIG_UART_0_ASYNC=y
# CONFIG_UART_0_NRF_HW_ASYNC=y
# CONFIG_UART_0_NRF_HW_ASYNC_TIMER=1

# ESB Config
CONFIG_ESB=y # 注意 使用了esb 射频方案就不能配置BLE的方案，会造成硬件资源上的冲突
CONFIG_ESB_MAX_PAYLOAD_LENGTH=252
CONFIG_ESB_NEVER_DISABLE_TX=n # to skip ramp up for maximum speed at the cost of energy
CONFIG_ESB_RX_FIFO_SIZE=8
CONFIG_ESB_TX_FIFO_SIZE=8
# 增加fifo 来提高缓冲，但同时会带来高延时和可能的高功耗（不正常的休眠）

#TWI config
CONFIG_I2C=y
CONFIG_NRFX_TWIM0=y # for LC and power management unit
 # nrf52840 only have i2c0,i2c1, and confilt with spi0, spi1, respectively
# CONFIG_CBPRINTF_FP_SUPPORT=y


CONFIG_WATCHDOG=n # 注意： watch dog 本质是一种软件上的复位设置，需要配置才能使用

CONFIG_RESET_ON_FATAL_ERROR=y # 在正式版本中需要打开来防止突然的错误

CONFIG_SYS_CLOCK_TICKS_PER_SEC=8192 
# # for real-time timestamp 
# CONFIG_COUNTER=y